name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: my-menu-service
  REGION: asia-east1
  # --- 資料庫環境變數 ---
  DB_TYPE: 'MYSQL'
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 步驟 1: 從倉庫中拉取最新的程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 步驟 2: 使用我們設定的 Secret 登入 Google Cloud
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 步驟 3: 建置並部署到 Cloud Run
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # 告訴 Cloud Run 從當前目錄的 Dockerfile 建置
          source: '.'
          # 將環境變數傳遞給 Cloud Run 服務
          env_vars: |
            DB_TYPE=${{ env.DB_TYPE }}
            DB_HOST=${{ env.DB_HOST }}
            DB_USER=${{ env.DB_USER }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_DATABASE=${{ env.DB_DATABASE }}
            GEMINI_API_KEY=${{ env.GEMINI_API_KEY }}